### ISSUE TITLE
Login Pages Not Opening in Obsidian 

### ISSUE THREAD

**Issue by lehelbeni** [MamoruDS/obsidian-open-link-with#11]
I am using this plugin as a browser in obsidian, the only problem is that when I want to log in (in-app view) it always opens the default browser not in Obsidian.

**Comment by alcance** [comment]
I am able to open in-app view but once i login into the website it removes my session and logout automatically.

**Comment by MamoruDS** [comment]
> I am using this plugin as a browser in obsidian, the only problem is that when I want to log in (in-app view) it always opens the default browser not in Obsidian.

This happens when you click on a link has attribute `target="_top"` , depending on the page you visit, such as the login button on the google home page

**Comment by MamoruDS** [comment]
In-app view enables web browsing by creating iframe, so session in views will not be saved or, even shared between views. So this feature is not applicable for browsing web pages that require login (cookies).

The best way to do this is to log in to your account in your favorite browser and save the url for access in obsidian.
