### ISSUE TITLE
breaks theme links

### ISSUE THREAD

**Issue by ksdavidc** [MamoruDS/obsidian-open-link-with#12]
When a theme is active in the theme manager, there is a link (usually to github, marked "how to use", or "features") that is broken by this plugin. I used divide & conquer plugin to isolate this plugin as the culprit, and turning it on and off clearly toggles the behavior. I tried various combination of modifier bindings as well, to no avail.

**Comment by ksdavidc** [comment]
just to be clear, this is in the obsidian theme manager, not the main editor, where the same links work fine.

**Comment by MamoruDS** [comment]
Thank you for raising this issue. The problem that some built-in clickable elements were broken by this plugin has been fixed in version 0.1.7.
