### ISSUE TITLE
Pop-out Blank Windows in obsidian v.0.15.6

### ISSUE THREAD

**Issue by BellTseng** [MamoruDS/obsidian-open-link-with#13]
When I dragged a view outside of the obsidian app to open the view in its own window (the new feature Pop-out Windows in ob v.0.15.6), there was only a blank window.

But, When I disable this plugin, the Pop-out Windows feature works.

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/38106775/178650276-8b5d2e65-e8e3-4bb2-95d7-6b81a50d1408.png">

**Comment by MamoruDS** [comment]
Thank you for raising this issue. Pop-out windows are supported in version 0.1.7.
