### ISSUE TITLE
some issues in the settings screen when installing plugins

### ISSUE THREAD

**Issue by hannesdelbeke** [MamoruDS/obsidian-open-link-with#19]
when installing a plugin, and reading the readme.
it is possible to see links in the readme.

these links are now intercepted by this plugin.
ideally this would be handled smoothly.

**priority: low**

this readme contains 2 types of links.
local, and external links

external links (red) open in a new tab in Obsidian when clicked.
but behind the settings screen, which is confusing.
(i have normal click set to open in new tab, which works fine when browsing notes normally)

external links open correctly when using external browser (for me that's middle mouse click)

internal links dont open correctly, and create a new empty window

<img width="981" alt="image" src="https://user-images.githubusercontent.com/3758308/213013700-3c9f9d50-ffac-4acb-a346-debf062e8560.png">

the new window it opens 
<img width="1047" alt="image" src="https://user-images.githubusercontent.com/3758308/213014069-8809c376-5cb9-43b9-9a21-9419c1e65fd8.png">

**Comment by MamoruDS** [comment]
Thanks for bringing this up, it should be fixed in the latest 0.1.10 release.

**Comment by hannesdelbeke** [comment]
i ll test it once the community plugin is updated :)
