### ISSUE TITLE
MacOS Custom Browser Configuration

### ISSUE THREAD

**Issue by jack04v** [MamoruDS/obsidian-open-link-with#2]
Greetings,
I've recently installed your Plugin (latest 0.1.3 version) on MacOS 10.15.7 and found that, while it works exactly as expected for the presets, setting up a custom browser seemed to fail to open on every configuration I tried.

From the given sample code & looking at the console log I've tested the following configurations:
```
{
    "[Browser]": [
        "/Applications/[Browser].app"
    ]
}
```
Result is a message that an opening is occurring in the console, but nothing actually happening.
```
{
    "[Browser]": [
        "[drivename]/Applications/[Browser].app/Contents/MacOS/[Browser]"
    ]
}
```
Result is also a message that an opening is occurring in the console, but nothing actually happening.
```
{
    "[Browser]": [
        "open -a [browser].app"
    ]
}
```
Result is the following error in console:
```
[open-link-with] failed to open:
'spawn' exited with code 127 when trying to open an external link with [browser].
```
The browsers I'm trying to add are Vivaldi & Waterfox, same exact results in both cases, with both capitalized and non capitalized filenames.

I apologies if there is something I'm doing wrong, but as much as I try, I can't seem to get the plugin working with custom browsers...

**Comment by MamoruDS** [comment]
Sorry for the late reply
After understanding your question, I tried to apply a customization setting for the Waterfox, similar to the second attempt you listed:
```json
{
    "waterfox": [
        "/Applications/Waterfox.app/Contents/MacOS/waterfox"
    ],
    "waterfox-private": [
        "/Applications/Waterfox.app/Contents/MacOS/waterfox",
        "--private-window"
    ]
}
```
and this seems to be working for me that Waterfox opened as I clicked a link as expected. 

Can you try to execute the command shown in the console in your terminal? The command should be a string after the `[open-link-with] opening: `. 

If you have any progress or problem, feel free to let me know.

**Comment by jack04v** [comment]
Apologies for my own belated reply,
I tested the command with your syntax and it works like a charm! 
```
{
    "waterfox": [
        "/Applications/Waterfox.app/Contents/MacOS/waterfox"
    ],
    "waterfox-private": [
        "/Applications/Waterfox.app/Contents/MacOS/waterfox",
        "--private-window"
    ],
    "vivaldi": [
        "/Applications/Vivaldi.app/Contents/MacOS/vivaldi"
    ],
    "vivaldi-private": [
        "/Applications/Vivaldi.app/Contents/MacOS/vivaldi",
        "-incognito"
    ]
}
```
Testing with both Waterfox & Vivaldi, regular & private/incognito mode everything works as it should would no errors in the developed console. 
```
{
    "waterfox": [
        "/Applications/Waterfox.app/Contents/MacOS/waterfox"
    ],
    "waterfox-private": [
        "/Applications/Waterfox.app/Contents/MacOS/waterfox",
        "--private-window"
    ]
}
```
My only suggestion would be to add this code snippet to the README file alongside the Windows one, otherwise the issue is resolved.
