### ISSUE TITLE
conflict with advanced slides

### ISSUE THREAD

**Issue by ksdavidc** [MamoruDS/obsidian-open-link-with#20]
This plugin appears to blocking the "open in browser" button in advanced slides plugin from activating. 

With all plugins but those two disabled, the link works with OLW off, and fails when OLW on.

log attached:
[obsidian.md-1674090867298.log](https://github.com/MamoruDS/obsidian-open-link-with/files/10452507/obsidian.md-1674090867298.log)

The issue could be with Advanced slides, and I will report it to them as well.

**Comment by MamoruDS** [comment]
Thanks for using this plugin. I noticed that there was an issue with the click detection in my plugin, and it should be fixed in the latest 0.1.10 release. Let me know if you run into any other problems.
