### ISSUE TITLE
issue with dark theme or CSS

### ISSUE THREAD

**Issue by hannesdelbeke** [MamoruDS/obsidian-open-link-with#21]
Thank you for this amazing plugin. It really makes my life a lot easier.

One issue I recently encountered, the dark theme / custom Obsidian CSS is applied to the website opened in the tab.
Most of the time this doesn't seem to be the case, but some websites have this.
affected  site is https://breadcrumbs-wiki.onrender.com/docs/Alternative%20Hierarchies/Hierarchy%20Notes

| in this case it makes the text unreadable <img width="1289" alt="image" src="https://user-images.githubusercontent.com/3758308/213548890-707c2ce8-7301-4bf5-92c2-ff7d1b61496f.png"> | it should look like this.  <img width="494" alt="image" src="https://user-images.githubusercontent.com/3758308/213549009-af7a4896-fdfd-4c7e-8224-36dbb13152bd.png">|
|-|-|

**Comment by MamoruDS** [comment]
Hey there! I've added a white background to the iframe for now. Since a webpage with no background is not the common, I might make it a changeable setting in a future update.
