### ISSUE TITLE
plug in opens link in both browsers

### ISSUE THREAD

**Issue by cvivcviv** [MamoruDS/obsidian-open-link-with#4]
I installed and enabled the plugin and selected the "chrome" drop down. I did not add anything under custom. When I click a link on the preview pane, the link will first open in Safari (MacOS) and then Chrome. So it is opening the link twice for one click. 

Do you know why this is happening? I am not sure how to troubleshoot. Thanks!

**Comment by MamoruDS** [comment]
Thank you for submitting this issue!
I have reproduced this error on the obsidian client with version v0.13 and I think it is due to obsidian changing the action when the link is clicked in its new version (client with version v0.12 does not have this problem). I will work on fixing this issue.

**Comment by MamoruDS** [comment]
This issue should gone after updating the plugin version to `0.1.4`.

**Comment by cvivcviv** [comment]
Awesome, thanks!
