### ISSUE TITLE
Feature request for multiple settings

### ISSUE THREAD

**Issue by tdwinki** [MamoruDS/obsidian-open-link-with#5]
It would be nice to have multiple settings with custom key bindings:

e.g.
Click to open with Chrome,
Shift + Click to open with Firefox

**Comment by MamoruDS** [comment]
Thank you for using this plugin and submitting this feature request. After updating to version `0.1.5`, you will be able to add custom modifier bindings in the plugin's settings menu, and you can learn more about this new feature [here](https://github.com/MamoruDS/obsidian-open-link-with#modifier-key-bindings).
