### ISSUE TITLE
Support Middle Click Links

### ISSUE THREAD

**Issue by dansmindspace** [MamoruDS/obsidian-open-link-with#6]
Middle clicking on a link should open in the same browser as selected, but opens in the system default browser.

**Comment by MamoruDS** [comment]
Thank you for raising this issue! Middle mouse button click is supported in version 0.1.5, and you can now customize mouse click behavior with new [modifier key bindings' setting](https://github.com/MamoruDS/obsidian-open-link-with#modifier-key-bindings).

**Comment by dansmindspace** [comment]
Thanks. Works great now.
